apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  replicas: 1
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapidemo
          image: hatcr.azurecr.io/restapidemo:v1
          ports:
            - containerPort: 8080